version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodatabase
    ports:
      - "27012:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - notification_network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6372:6379"
    networks:
      - notification_network
  fake-smtp:
    image: haravich/fake-smtp-server
    container_name: fake_smtp
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - notification_network

volumes:
  mongodb_data:
  redis_data:

networks:
  notification_network:
